github_api_token: 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
plot_color: blue
plot_title: GitHub Data Analysis
plot_x_axis_title: X-Axis
plot_y_axis_title: Y-Axis
figure_size: [10, 6]
default_save_path: ./output/A2296

