github_api_token: USERS_TOKEN
plot_color: blue
plot_title: Top Followed GitHub Users
plot_x_axis_title: Followers (Placeholder)
plot_y_axis_title: Usernames
figure_size: [10, 6]
default_save_path: ./

